name: very_good_weather
description: A Very Good Weather Application
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  flutter_svg: ^1.0.1
  intl: ^0.17.0
  weather_api:
    path: packages/weather_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  mockingjay: ^0.2.0
  mocktail: ^0.2.0
  mocktail_image_network: ^0.2.0
  plugin_platform_interface: ^2.0.2
  url_launcher_platform_interface: ^2.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/weather_icons/